name: work_o_clock
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  table_calendar: ^3.1.2
  aligned_dialog: ^0.0.7
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  get: ^4.6.6
  file_picker: ^8.0.0+1
  provider: ^6.1.2
  image_picker: ^1.0.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/logos/
    - assets/icons/

  fonts:
    # - family: Tw-Cen-MT
    #   fonts:
    #     - asset: assets/fonts/Tw-Cen-MT.ttf
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost/static/Jost-Regular.ttf
          style: normal
        - asset: assets/fonts/Jost/static/Jost-Bold.ttf
        - asset: assets/fonts/Jost/static/Jost-Italic.ttf
          style: italic
